"""Add composite indexes for performance optimization

Revision ID: 134d2efdb7f9
Revises: a24cee49bb36
Create Date: 2026-01-02 11:36:19.802852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134d2efdb7f9'
down_revision: Union[str, None] = 'a24cee49bb36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_job_field_name', 'extracted_fields', ['job_id', 'field_name'], unique=False)
    op.create_index('idx_status_created', 'jobs', ['status', 'created_at'], unique=False)
    op.create_index('idx_user_created', 'jobs', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_user_status', 'jobs', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_status', table_name='jobs')
    op.drop_index('idx_user_created', table_name='jobs')
    op.drop_index('idx_status_created', table_name='jobs')
    op.drop_index('idx_job_field_name', table_name='extracted_fields')
    # ### end Alembic commands ###
