"""add_file_hash_to_jobs

Revision ID: a24cee49bb36
Revises: 006
Create Date: 2025-12-30 12:49:09.455747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24cee49bb36'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_contacts_created_at'), table_name='contacts')
    op.drop_index(op.f('idx_contacts_email'), table_name='contacts')
    op.create_index(op.f('ix_contacts_created_at'), 'contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.add_column('jobs', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('jobs', sa.Column('fraud_analysis', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_jobs_file_hash'), 'jobs', ['file_hash'], unique=False)
    op.add_column('users', sa.Column('pending_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_change_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_change_token_expires', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_email_change_token'), 'users', ['email_change_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_change_token'), table_name='users')
    op.drop_column('users', 'email_change_token_expires')
    op.drop_column('users', 'email_change_token')
    op.drop_column('users', 'pending_email')
    op.drop_index(op.f('ix_jobs_file_hash'), table_name='jobs')
    op.drop_column('jobs', 'fraud_analysis')
    op.drop_column('jobs', 'file_hash')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_created_at'), table_name='contacts')
    op.create_index(op.f('idx_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('idx_contacts_created_at'), 'contacts', ['created_at'], unique=False)
    # ### end Alembic commands ###
